-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 21:34:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `PermisoEditarSusDatosPersonales` INT NULL,
  `PermisoEditarDatosPersonalesOtros` INT NULL,
  `PermisoEditarObservacionesOtros` INT NULL,
  `PermisoVerObservacionesOtros` INT NULL,
  `PermisoEditarCalificacionesSusAlumnos` INT NULL,
  `PermisoEditarDatosPersonalesAlumnoaCargo` INT NULL,
  `PermisoVerCalificacionesAlumnoaCargo` INT NULL,
  `PermisoVerSusCalificaciones` INT NULL,
  `PermisoGestionarEscuela` INT NULL,
  `PermisoInscribirAlumno` INT NULL,
  `PermisoInscribirDocente` INT NULL,
  `PermisoGestionarBiblioteca` INT NULL,
  PRIMARY KEY (`idPermisos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPerfil` (
  `idTipoPerfil` INT NOT NULL,
  `PerfilDesc` VARCHAR(45) NULL,
  `Permisos_idPermisos` INT NOT NULL,
  PRIMARY KEY (`idTipoPerfil`),
  INDEX `fk_TipoPerfil_Permisos1_idx` (`Permisos_idPermisos` ASC),
  CONSTRAINT `fk_TipoPerfil_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `mydb`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `TipoPerfil_idTipoPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_TipoPerfil1_idx` (`TipoPerfil_idTipoPerfil` ASC),
  CONSTRAINT `fk_Usuario_TipoPerfil1`
    FOREIGN KEY (`TipoPerfil_idTipoPerfil`)
    REFERENCES `mydb`.`TipoPerfil` (`idTipoPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `CodigoPostal` INT NULL,
  PRIMARY KEY (`idLocalidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(15) NULL,
  `dni` VARCHAR(9) NOT NULL,
  `cuil` VARCHAR(15) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_Persona_Localidad1_idx` (`Localidad_idLocalidad` ASC),
  INDEX `fk_Persona_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Persona_Localidad1`
    FOREIGN KEY (`Localidad_idLocalidad`)
    REFERENCES `mydb`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel` (
  `idNivel` INT NOT NULL AUTO_INCREMENT,
  `GradoCurso` VARCHAR(45) NULL,
  `Division` VARCHAR(45) NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DatosPersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatosPersonales` (
  `idDatosPersonales` INT NOT NULL AUTO_INCREMENT,
  `EstadoCivil` VARCHAR(45) NULL,
  `CantidadHijos` INT NULL,
  `SituacionPadre` VARCHAR(45) NULL,
  `SituacionMadre` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDatosPersonales`),
  INDEX `fk_DatosPersonales_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_DatosPersonales_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domicilio` (
  `idDomicilio` INT NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Piso` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Unidad` VARCHAR(45) NULL,
  `Barrio` VARCHAR(45) NULL,
  `TipodeVivienda` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDomicilio`),
  INDEX `fk_Domicilio_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Domicilio_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DatosContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatosContacto` (
  `idDatosContacto` INT NOT NULL AUTO_INCREMENT,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `telefono3` VARCHAR(45) NULL,
  `telefono4` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDatosContacto`),
  INDEX `fk_DatosContacto_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_DatosContacto_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudios` (
  `idEstudios` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(45) NULL,
  `Institucion` VARCHAR(45) NULL,
  `Titulo` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idEstudios`),
  INDEX `fk_Estudios_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Estudios_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tecnologia` (
  `idTecnologia` INT NOT NULL AUTO_INCREMENT,
  `DisponePc` INT NULL,
  `AccesoInternet` INT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idTecnologia`),
  INDEX `fk_TecnologiadePersona_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_TecnologiadePersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Deportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deportes` (
  `idDeportes` INT NOT NULL AUTO_INCREMENT,
  `PracticaDeportesSiNo` INT NULL,
  `DeporteDescripcion` VARCHAR(200) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDeportes`),
  INDEX `fk_DeportesdePersona_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_DeportesdePersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idioma` (
  `idIdioma` INT NOT NULL AUTO_INCREMENT,
  `Ingles` VARCHAR(45) NULL,
  `Aleman` VARCHAR(45) NULL,
  `Frances` VARCHAR(45) NULL,
  `Italiano` VARCHAR(45) NULL,
  `Portugues` VARCHAR(45) NULL,
  `Chino` VARCHAR(45) NULL,
  `Otros` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idIdioma`),
  INDEX `fk_IdiomadePersona_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_IdiomadePersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Discapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discapacidad` (
  `idDiscapacidad` INT NOT NULL AUTO_INCREMENT,
  `DiscapacidadDesc` VARCHAR(200) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDiscapacidad`),
  INDEX `fk_DiscapacidaddePersona_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_DiscapacidaddePersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`FechaNacimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FechaNacimiento` (
  `idFechaNacimiento` INT NOT NULL AUTO_INCREMENT,
  `FechaNacimiento` DATE NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idFechaNacimiento`),
  INDEX `fk_FechaNacimientoPersona_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_FechaNacimientoPersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT,
  `InscripcionFecha` DATE NULL,
  `Nivel_idNivel` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idInscripcion`),
  INDEX `fk_Inscripcion_Persona1_idx` (`Persona_idPersona` ASC),
  INDEX `fk_Inscripcion_Nivel1_idx` (`Nivel_idNivel` ASC),
  CONSTRAINT `fk_Inscripcion_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Nivel1`
    FOREIGN KEY (`Nivel_idNivel`)
    REFERENCES `mydb`.`Nivel` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `TipoCargo` INT NULL,
  `Escuela` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `DecretoDesignacion` VARCHAR(45) NULL,
  `SituaciondeRevistaDesc` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  `CantidadHorasCatedra` INT NULL,
  PRIMARY KEY (`idCargo`),
  INDEX `fk_Cargo_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Cargo_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoBeca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoBeca` (
  `idTipoBeca` INT NOT NULL AUTO_INCREMENT,
  `BecaDesc` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  PRIMARY KEY (`idTipoBeca`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Persona_has_TipoBeca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_has_TipoBeca` (
  `Persona_idPersona` INT NOT NULL,
  `TipoBeca_idTipoBeca` INT NOT NULL,
  PRIMARY KEY (`Persona_idPersona`, `TipoBeca_idTipoBeca`),
  INDEX `fk_Persona_has_TipoBeca_TipoBeca1_idx` (`TipoBeca_idTipoBeca` ASC),
  INDEX `fk_Persona_has_TipoBeca_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Persona_has_TipoBeca_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_TipoBeca_TipoBeca1`
    FOREIGN KEY (`TipoBeca_idTipoBeca`)
    REFERENCES `mydb`.`TipoBeca` (`idTipoBeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `Cargo_idCargo` INT NOT NULL,
  `idAsignatura` INT NOT NULL AUTO_INCREMENT,
  `AsignaturaDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `fk_Asignatura_Cargo1_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Asignatura_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calificaciones` (
  `idCalificaciones` INT NOT NULL AUTO_INCREMENT,
  `1erTrimestre` FLOAT NULL,
  `2doTrimestre` FLOAT NULL,
  `3erTrimestre` FLOAT NULL,
  `Anio` YEAR NULL,
  `idDocenteResponsable` INT NOT NULL,
  `idAsignatura` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  PRIMARY KEY (`idCalificaciones`),
  INDEX `fk_Calificaciones_Persona1_idx` (`idAlumno` ASC),
  INDEX `fk_Calificaciones_Cargo1_idx` (`idDocenteResponsable` ASC),
  INDEX `fk_Calificaciones_Asignatura1_idx` (`idAsignatura` ASC),
  CONSTRAINT `fk_Calificaciones_Persona1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificaciones_Cargo1`
    FOREIGN KEY (`idDocenteResponsable`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificaciones_Asignatura1`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoRecuperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoRecuperacion` (
  `idTipoRecuperacion` INT NOT NULL AUTO_INCREMENT,
  `TipoRecuperacionDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoRecuperacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Recuperaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recuperaciones` (
  `idRecuperaciones` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `RecuperacionesDesc` VARCHAR(45) NULL,
  `idTipoRecuperacion` INT NOT NULL,
  `idCalificaciones` INT NOT NULL,
  PRIMARY KEY (`idRecuperaciones`),
  INDEX `fk_Recuperaciones_Calificaciones1_idx` (`idCalificaciones` ASC),
  INDEX `fk_Recuperaciones_TipoRecuperacion1_idx` (`idTipoRecuperacion` ASC),
  CONSTRAINT `fk_Recuperaciones_Calificaciones1`
    FOREIGN KEY (`idCalificaciones`)
    REFERENCES `mydb`.`Calificaciones` (`idCalificaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recuperaciones_TipoRecuperacion1`
    FOREIGN KEY (`idTipoRecuperacion`)
    REFERENCES `mydb`.`TipoRecuperacion` (`idTipoRecuperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CedulaDocente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CedulaDocente` (
  `idCedulaDocente` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Calificacion` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCedulaDocente`),
  INDEX `fk_CedulaDocente_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_CedulaDocente_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`HorarioActividadDocente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HorarioActividadDocente` (
  `idHorarioActividadDocente` INT NOT NULL AUTO_INCREMENT,
  `DiaSemana` VARCHAR(45) NULL,
  `HorarioInicio` TIME NULL,
  `HorarioFin` TIME NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idHorarioActividadDocente`),
  INDEX `fk_HorarioActividad_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_HorarioActividad_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Licencia` (
  `idLicencia` INT NOT NULL AUTO_INCREMENT,
  `LicenciaDesc` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idLicencia`),
  INDEX `fk_Licencia_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Licencia_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`FichaTutorAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FichaTutorAlumno` (
  `idFichaTutorAlumno` INT NOT NULL AUTO_INCREMENT,
  `idTutor` INT NULL,
  `idAlumno` INT NULL,
  `RelacionDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idFichaTutorAlumno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Observaciones` (
  `idObservaciones` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Hora` VARCHAR(10) NULL,
  `ObservacionDesc` VARCHAR(200) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idObservaciones`),
  INDEX `fk_Observaciones_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Observaciones_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo_has_Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo_has_Nivel` (
  `Cargo_idCargo` INT NOT NULL AUTO_INCREMENT,
  `Nivel_idNivel` INT NOT NULL,
  PRIMARY KEY (`Cargo_idCargo`, `Nivel_idNivel`),
  INDEX `fk_Cargo_has_Nivel1_Nivel1_idx` (`Nivel_idNivel` ASC),
  INDEX `fk_Cargo_has_Nivel1_Cargo1_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Cargo_has_Nivel1_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_Nivel1_Nivel1`
    FOREIGN KEY (`Nivel_idNivel`)
    REFERENCES `mydb`.`Nivel` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Nivel_has_Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel_has_Asignatura` (
  `Nivel_idNivel` INT NOT NULL AUTO_INCREMENT,
  `Asignatura_idAsignatura` INT NOT NULL,
  PRIMARY KEY (`Nivel_idNivel`, `Asignatura_idAsignatura`),
  INDEX `fk_Nivel_has_Asignatura_Asignatura1_idx` (`Asignatura_idAsignatura` ASC),
  INDEX `fk_Nivel_has_Asignatura_Nivel1_idx` (`Nivel_idNivel` ASC),
  CONSTRAINT `fk_Nivel_has_Asignatura_Nivel1`
    FOREIGN KEY (`Nivel_idNivel`)
    REFERENCES `mydb`.`Nivel` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nivel_has_Asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`FichaSocioBiblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FichaSocioBiblioteca` (
  `idFichaSocioBiblioteca` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `TipoSocio` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idFichaSocioBiblioteca`),
  INDEX `fk_FichaSocioBiblioteca_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_FichaSocioBiblioteca_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `PaisDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `idEditorial` INT NOT NULL AUTO_INCREMENT,
  `EditorialDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(200) NULL,
  `Numero` INT NULL,
  `Paginas` INT NULL,
  `FechaPublicacion` DATE NULL,
  `ISBN` VARCHAR(45) NULL,
  `LinkImagen` VARCHAR(200) NULL,
  `LinkDescarga` VARCHAR(200) NULL,
  `Pais_idPais` INT NOT NULL,
  `Editorial_idEditorial` INT NOT NULL,
  `CantidadVecesPedidas` INT NULL,
  `Estado` INT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_Libro_Pais1_idx` (`Pais_idPais` ASC),
  INDEX `fk_Libro_Editorial1_idx` (`Editorial_idEditorial` ASC),
  CONSTRAINT `fk_Libro_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`Editorial_idEditorial`)
    REFERENCES `mydb`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `FechaPrestamo` DATE NULL,
  `FechaEntrega` DATE NULL,
  `FechaDevolucion` DATE NULL,
  `idFichaSocioBiblioteca` INT NOT NULL,
  `idDocenteResponsable` INT NOT NULL,
  `idLibro` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Cargo1_idx` (`idDocenteResponsable` ASC),
  INDEX `fk_Prestamo_FichaSocioBiblioteca1_idx` (`idFichaSocioBiblioteca` ASC),
  INDEX `fk_Prestamo_Libro1_idx` (`idLibro` ASC),
  CONSTRAINT `fk_Prestamo_Cargo1`
    FOREIGN KEY (`idDocenteResponsable`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_FichaSocioBiblioteca1`
    FOREIGN KEY (`idFichaSocioBiblioteca`)
    REFERENCES `mydb`.`FichaSocioBiblioteca` (`idFichaSocioBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `GeneroDesc` VARCHAR(250) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `AutorDesc` VARCHAR(250) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Control` (
  `idControl` INT NOT NULL AUTO_INCREMENT,
  `NombreTablaEditada` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idControl`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Libro_has_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro_has_Genero` (
  `Libro_idLibro` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`Libro_idLibro`, `Genero_idGenero`),
  INDEX `fk_Libro_has_Genero_Genero1_idx` (`Genero_idGenero` ASC),
  INDEX `fk_Libro_has_Genero_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_Libro_has_Genero_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Genero_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Libro_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro_has_Autor` (
  `Libro_idLibro` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Libro_idLibro`, `Autor_idAutor`),
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_Libro_has_Autor_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_Libro_has_Autor_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo_has_HorarioActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo_has_HorarioActividad` (
  `Cargo_idCargo` INT NOT NULL,
  `HorarioActividad_idHorarioActividad` INT NOT NULL,
  PRIMARY KEY (`Cargo_idCargo`, `HorarioActividad_idHorarioActividad`),
  INDEX `fk_Cargo_has_HorarioActividad_HorarioActividad1_idx` (`HorarioActividad_idHorarioActividad` ASC),
  INDEX `fk_Cargo_has_HorarioActividad_Cargo1_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Cargo_has_HorarioActividad_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_HorarioActividad_HorarioActividad1`
    FOREIGN KEY (`HorarioActividad_idHorarioActividad`)
    REFERENCES `mydb`.`HorarioActividadDocente` (`idHorarioActividadDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`HorarioActividadNivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HorarioActividadNivel` (
  `idHorarioActividadNivel` INT NOT NULL AUTO_INCREMENT,
  `DiaSemana` VARCHAR(45) NULL,
  `HorarioInicio` TIME NULL,
  `HorarioFin` TIME NULL,
  `Nivel_idNivel` INT NOT NULL,
  PRIMARY KEY (`idHorarioActividadNivel`),
  INDEX `fk_HorarioActividadNivel_Nivel1_idx` (`Nivel_idNivel` ASC),
  CONSTRAINT `fk_HorarioActividadNivel_Nivel1`
    FOREIGN KEY (`Nivel_idNivel`)
    REFERENCES `mydb`.`Nivel` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
